apiVersion: v1
kind: Pod
metadata:
  name: shiny
spec: 
  containers:
    - image: docker.io/th1460/shiny-example
      name: shiny
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      ports: 
        - containerPort: 8080
          name: http
          protocol: TCP  
