apiVersion: v1
kind: Pod
metadata:
  name: shiny
spec: 
  containers:
    - image: docker.io/th1460/shiny-example
      name: shiny
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports: 
        - containerPort: 8080
          name: http
          protocol: TCP  
