apiVersion: v1
kind: Pod
metadata:
  name: shiny
  labels:
    env: dev
spec: 
  containers:
    - image: docker.io/th1460/shiny-example
      name: shiny
      ports: 
        - containerPort: 8080
          name: http
          protocol: TCP 
